inherit_from: .rubocop_todo.yml

AllCops:
  # 除外するディレクトリ（自動生成されたファイル）
  # デフォルト設定にある"vendor/**/*"が無効化されないように記述
  Exclude:
    - bin/*
    - db/schema.rb
    - db/migrate/*
    - vendor/**/*
  DisplayCopNames: true

# classやmoduleの先頭コメント
Documentation:
  Enabled: false

Security/Open:
  Enabled: false

# 日本語でのコメント
Style/AsciiComments:
  Enabled: false

# "Missing top-level class documentation comment."を無効
Style/Documentation:
  Enabled: false

# この2つは単発で動かすのが分かっているので Objectを汚染しても問題ない
Style/MixinUsage:
  Exclude:
    - bin/setup
    - bin/update

# "Prefer single-quoted strings when you don't need string interpolation or special symbols."を無効
Style/StringLiterals:
  Enabled: false

# "Line is too long"を無効
Metrics/LineLength:
  Enabled: false

# ブロック内の行数
Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - config/**/*
